config/routes.rb
Rails.application.routes.draw do
  resources :lab_reports
  root to: "lab_reports#index"
  get '/lab_reports/:id/add_grade', to: 'lab_reports#add_grade', as: 'add_grade_lab_report'
  patch '/lab_reports/:id/update_grade', to: 'lab_reports#update_grade', as: 'update_grade_lab_report'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lab_report.rb
class LabReport < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: {maximum:250}
    validates :description, length: {maximum:500}
    validates :grade, length: {maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :lab_reports

    validates :first_name, presence: true, length: {maximum: 100}
    validates :last_name, presence: true, length: {maximum: 100}
    validates :email, uniqueness: true, presence: true, length: {maximum:150}, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController
  before_action :set_lab_report, only: %i[ show edit update destroy add_grade update_grade]

  # GET /lab_reports or /lab_reports.json
  def index
    @lab_reports = LabReport.all
  end

  # GET /lab_reports/1 or /lab_reports/1.json
  def show
  end

  # GET /lab_reports/new
  def new
    @lab_report = LabReport.new
    @users = User.all

  end

  # GET /lab_reports/1/edit
  def edit
  end

  # POST /lab_reports or /lab_reports.json
  def create
    @lab_report = LabReport.new(lab_report_params)
    @users = User.all

    respond_to do |format|
      if @lab_report.save
        format.html { redirect_to lab_report_url(@lab_report), notice: "Отчет успешно создан." }
        format.json { render :show, status: :created, location: @lab_report}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lab_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lab_reports/1 or /lab_reports/1.json
  def update
    respond_to do |format|
      if @lab_report.update(lab_report_params)
        format.html { redirect_to lab_report_url(@lab_report), notice: "Отчет успешно изменен." }
        format.json { render :show, status: :ok, location: @lab_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lab_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lab_reports/1 or /lab_reports/1.json
  def destroy
    @lab_report.destroy

    respond_to do |format|
      format.html { redirect_to lab_reports_url, notice: "Отчет успешно удален." }
      format.json { head :no_content }
    end
  end

  # Метод для добавления оценки
  def add_grade
  end

  # Метод для сохранения оценки
  def update_grade 
    respond_to do |format|
      if @lab_report.update(lab_report_params_grade)
        format.html { redirect_to lab_report_url(@lab_report), notice: "Оценка добавлена." }
        format.json { render :show, status: :ok, location: @lab_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lab_report.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab_report
      @lab_report = LabReport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lab_report_params
      params.require(:lab_report).permit(:user_id, :title, :description)
    end

    def lab_report_params_grade 
      params.require(:lab_report).permit(:grade)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "Пользователь успешно создан." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lab_reports/_form.html.erb
<%= form_with(model: lab_report) do |form| %>
  <% if lab_report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lab_report.errors.count, "error") %> prohibited this lab_report from being saved:</h2>

      <ul>
        <% lab_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.text_field :grade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lab_reports/_lab_report.html.erb
<div id="<%= dom_id lab_report %>">
  <p>
    <strong>User:</strong>
    <%= lab_report.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= lab_report.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= lab_report.description %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= lab_report.grade %>
  </p>

</div>

app/views/lab_reports/add_grade.html.erb
<%= form_with(model: @lab_report, url: update_grade_lab_report_path) do |form| %>
<div style="text-align: center; padding: 10rem 0 15px 0;">
  <label style="margin-right: 12rem;">Оценка</label>
  <select style="width: 20%;" name="lab_report[grade]" id="lab_report_grade">
    <option value="A">A</option>
    <option value="B">B</option>
    <option value="C">C</option>
    <option value="D">D</option>
    <option value="E">E</option>
    <option value="FX">FX</option>
    <option value="F">F</option>
  </select>
</div>
<div style="text-align: center;">
    <%= form.submit "Сохранить", style: 'border: 1px solid #535353; background-color: #ffffff; color: black' %>
  </div>
<% end %>

app/views/lab_reports/edit.html.erb
<h1>Изменить лабораторную работу</h1>

<%= render "form", lab_report: @lab_report %>

<br>

<div>
  <%= link_to "Показать эту лабораторную работу", @lab_report %> |
  <%= link_to "Вернуться к списку лабораторных работ", lab_reports_path %>
</div>

app/views/lab_reports/index.html.erb
<p style="color: green"><%= notice %></p>

<div style="text-align:right; margin-right: 60px;">
  <button style="border: 1px solid #535353;
  background-color: #ffffff;">
    <%= link_to "Создать пользователя", new_user_path,  style: 'color: black;' %>
 </button>
</div>

<div>
  <h1 style="text-align:center">Отчет лабораторных работ</h1>
  <div style="margin-left: 60px; margin-right: 60px">
  <button style="border: 1px solid #535353;
  background-color: #ffffff;">
  <%= link_to "Создать новый отчет", new_lab_report_path, style: 'color: black;' %>
  </button>
  </div>
  
  <div style="margin-left: 60px; margin-right: 60px">
    <% @lab_reports.each do |lab_report| %>
        <div>
          <h5 style="margin-bottom: 0px;"> Название: <%= lab_report.title %></h5>
          <p style="font-style: italic; margin-bottom: 5px; margin-top: 0px;">
          Студент: <%= lab_report.user.first_name%> <%= lab_report.user.last_name%>(<%= lab_report.user.email%>)
          </p>
          <p style="font-weight: 900; font-size: 15px; margin-top: 0px;"><%= lab_report.description %></p>
            <div style="display: flex; flex-wrap: wrap; margin-right: -5px; margin-left: -5px;">
              <% if lab_report.grade.blank? %>
                <div style="padding-right: 5px; padding-left: 5px;">
                  <button style="border: 1px solid #535353;
                  background-color: #ffffff;">
                    <%= link_to 'Добавить оценку', add_grade_lab_report_path(lab_report), style: 'color: black;' %>
                  </button>
                </div>
              <% else %>
                <div style="padding-right: 5px; padding-left: 5px; margin-top: -8px;">
                  <p style="font-weight: 900; font-size: 15px">Оценка: <%= lab_report.grade %></p>
                </div>
              <% end %>
              <div style="padding-right: 5px; padding-left: 5px;">
                <button style="border: 1px solid #535353;
                background-color: #ffffff;">
                  <%= link_to "Показать этот отчет", lab_report, style: 'color: black;' %>
                </button>
              </div>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/lab_reports/new.html.erb
<%= form_with(model: @lab_report, url: lab_reports_path) do |form| %>
<div style="text-align: center;padding: 10rem 0 15px 0;">
  <div>
    <label style="margin-right: 6rem;">Название лабораторной работы</label>
    <input style="width: 25%;" type="text" name="lab_report[title]" id="lab_report_title">
  </div>
  <div>
    <label style="margin-right: 15rem;">Описание</label>
    <input style="width: 25%;height: 100px;" type="text" name="lab_report[description]" id="lab_report_description">
  </div>
  <div style="margin-bottom: 5rem;">
    <label style="margin-right: 13rem;">Пользователь</label>
    <select style="width: 25%;" name="lab_report[user_id]" id="lab_report_user_id">
        <% @users.each do |user| %>
      <option value="<%= user.id %>">
      <%= user.first_name %> <%= user.last_name %>
      </option>
        <% end %>
    </select>
  </div>
  <div class="actions">
      <%= form.submit "Создать", style: 'border: 1px solid #535353; background-color: #ffffff; color: black' %>
    </div>
</div>
<% end %>

app/views/lab_reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lab_report %>

<div>
  <%= link_to "Изменить эту лабораторную работу", edit_lab_report_path(@lab_report) %> |
  <%= link_to "Вернуться к списку лабораторных работ", lab_reports_path %>

  <%= button_to "Удалить эту лабораторную работу", @lab_report, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Minified version -->
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

    <!-- Un-Minified version -->
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="grid-template-columns: 0;
    margin: 0; 
    font-size: 0.875rem;
    font-weight: 400;
    line-height: 1.5;
    color: black;
    text-align: left;
    background-color: #ffffff;">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<div style="text-align:center;">
  <h1>Пользователи</h1>
  <%= link_to "New user", new_user_path %>

  <div id="users">
    <% @users.each do |user| %>
      <%= render user %>
      <p>
        <%= link_to "Show this user", user %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1 style="text-align:center;">Новый Пользователь</h1>

<div style="text-align:center;">
<%= render "form", user: @user %>
</div>

<br>

<div style="text-align:center;">
  <%= link_to "Вернуться ко всем пользователям", users_path %>
  <br>
  <%= link_to "Вернуться к списку лабораторных работ", lab_reports_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>